---
- name: check users exits
  become: true
  getent:
    database: passwd
    key: "{{ user }}"
  loop: "{{ git_global_config | map (attribute='username') | list }}"
  loop_control:
    loop_var: user

- name: deploy userspecific .gitconfig
  become: true
  template:
    src: gitconfig.j2
    dest: "/home/{{ user.username }}/.gitconfig"
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: '640'
  loop: "{{ git_global_config | default([]) }}"
  loop_control:
    loop_var: user

- name: configure git-clone-init
  include_tasks: clone_init.yml
  loop: "{{ git_global_config | default([]) }}"
  loop_control:
    loop_var: user
  when:
    - user.clone_init_domains is defined
    - user.config.init.templatedir is defined